Reorganize projects
zio/zio-macros pull request #30
Opened 2019-10-22 19:37 UTC by ioleo

Fixes #26 

Also includes minor tweaks:
- updated readme
- added warning suppression via silencer plugin

2019-10-22 21:45 UTC, ioleo commented
Rebased to include `delegate/patch`

2019-10-23 18:36 UTC, mschuwalow requested changes
Looks good. Only one small remark.

Thanks for taking care of this!

2019-10-23 18:36 UTC, mschuwalow commented on build.sbt
> +    coreExamples.jvm,
I believe coreTests are missing here

2019-10-23 18:36 UTC, mschuwalow commented on core/shared/src/main/scala/zio/macros/core/ModulePattern.scala
> +  @silent("pattern var [^\\s]+ in method unapply is never used")
nice

2019-10-24 11:16 UTC, merged